version: '3.6'

name: blog-admin

################################################################################
# NETWORKS
################################################################################
networks:
  dev:

################################################################################
# SERVICES
################################################################################
services:
  blog-admin-dev:
    container_name: blog-admin-dev
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      target: dev
    ports:
      - '5001:5001'
    
    # stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_OPTIONS=--openssl-legacy-provider

    networks:
      - dev
    volumes:
      - .:/usr/app/admin
      - ./node_modules:/usr/app/admin/node_modules

  blog-admin-prod:
    container_name: blog-admin-prod
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      target: prod
    ports:
      - '5021:80'
    
    # stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_OPTIONS=--openssl-legacy-provider

    networks:
      - dev