version: '3.6'

name: board

################################################################################
# NETWORKS
################################################################################
networks:
  dev:
    external: true
  nginxproxymanager_softeam-net:
    external: true

################################################################################
# SERVICES
################################################################################
services:
  board-dev:
    container_name: admin-dev
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      target: dev
    ports:
      - '5001:5001'
    
    # stdin_open: true
    environment:
      - API_URL=http://dev:5010
      - CHOKIDAR_USEPOLLING=true
      - NODE_OPTIONS=--openssl-legacy-provider

    networks:
      - dev
      - nginxproxymanager_softeam-net
    volumes:
      - .:/usr/app/admin
      - ./node_modules:/usr/app/admin/node_modules

  board-prod:
    container_name: admin-prod
    build:
      context: .
      dockerfile: Dockerfile
      network: host
      target: prod
    ports:
      - '5021:80'
    
    # stdin_open: true
    environment:
      - API_URL=http://prod:5020
      - CHOKIDAR_USEPOLLING=true
      - NODE_OPTIONS=--openssl-legacy-provider

    networks:
      - nginxproxymanager_softeam-net