version: '3'

################################################################################
# NETWORKS
################################################################################
networks:
  prod:             # Network name given  for this stack
    name: prod-network       # Network pre existing name Compose has to look to connect your app's container

################################################################################
# SERVICES
################################################################################
services:
  admin-prod:
    container_name: admin-prod
    image: registry.fenikz.tk/admin-prod:1.0.0
    ports:
      - '8887:8887'
    
    # stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_OPTIONS=--openssl-legacy-provider

    networks:
      - prod
      # - ./node_modules:/usr/src/service/node_modules