export const ARTICLES = {
  CLAP: {
    FAILURE: 'ARTICLES.CLAP.FAILURE',
    SUCCESS: 'ARTICLES.CLAP.SUCCESS'
  },

  COMMENT: {
    FAILURE: 'ARTICLES.COMMENT.FAILURE',
    SUCCESS: 'ARTICLES.COMMENT.SUCCESS'
  },

  LOAD: {
    FAILURE: 'ARTICLES.LOAD.FAILURE',
    SUCCESS: 'ARTICLES.LOAD.SUCCESS'
  },

  PUBLISH: {
    FAILURE: 'ARTICLES.PUBLISH.FAILURE',
    SUCCESS: 'ARTICLES.PUBLISH.SUCCESS'
  },

  UNCLAP: {
    FAILURE: 'ARTICLES.UNCLAP.FAILURE',
    SUCCESS: 'ARTICLES.UNCLAP.SUCCESS'
  },

  VIEW: {
    FAILURE: 'ARTICLES.VIEW.FAILURE',
    SUCCESS: 'ARTICLES.VIEW.SUCCESS'
  }
}

export const AUTH = {
  FOLLOW: {
    FAILURE: 'AUTH.FOLLOW.FAILURE',
    SUCCESS: 'AUTH.FOLLOW.SUCCESS'
  },

  SET: {
    PROFILE: {
      FAILURE: 'AUTH.SET.PROFILE.FAILURE',
      SUCCESS: 'AUTH.SET.PROFILE.SUCCESS'
    },

    USER: {
      FAILURE: 'AUTH.SET.USER.FAILURE',
      SUCCESS: 'AUTH.SET.USER.SUCCESS'
    }
  },

  VIEW: {
    FAILURE: 'AUTH.VIEW.FAILURE',
    SUCCESS: 'AUTH.VIEW.SUCCESS'
  }
}

export const USERS = {
  GET: {
    ALL: {
      FAILURE: 'USERS.GET.ALL.FAILURE',
      SUCCESS: 'USERS.GET.ALL.SUCCESS'
    },
    ONE: {
      FAILURE: 'USERS.GET.ONE.FAILURE',
      SUCCESS: 'USERS.GET.ONE.SUCCESS'
    }
  }
}

export const TOGGLE = {
  MODAL: {
    FAILURE: 'TOGGLE.MODAL.FAILURE',
    SUCCESS: 'TOGGLE.MODAL.SUCCESS'
  }
}
